### PR TITLE
Refactor existing tests and add new ones

### LINKED ISSUE #144: Add continuous integration tool (CI)
# Summary

#304 

In order to improve our deploy process, we want to integrate an automation tool.

This tool should check few routines like:
- Merge from `feature-branch` to `development`.
   - If tests are `OK`, allow merge 
- Merge from `development` to `master`
    -  If tests are `OK` automatically merge

## Possible solutions
- [Github Actions](https://github.com/features/actions)
- [GitLab CI/CD for GitHub](https://about.gitlab.com/solutions/github/)
- [CircleCI](https://circleci.com/)
- [TravisCI](https://travis-ci.org/)
- [CloudBees CodeShip](https://www.cloudbees.com/products/codeship)
- [Jenkins.io](https://www.jenkins.io/)
- [Cypress.io](https://www.cypress.io/)

# Output

T.B.D

### PR DESCRIPTION
**Pull request by wlsf82**
For more details, read the commit messages.

See the tests running:

https://user-images.githubusercontent.com/2768415/141815888-eb6912f4-615d-4f3b-b1e7-a05868e0b80f.mp4

https://user-images.githubusercontent.com/2768415/141815895-c2f9bac4-c4f4-4a4e-8393-4427318de9ec.mp4

Cc @ArthurMota9, @idmarjr, and @miltonbsn.

### CODE REVIEW

**Comment by wlsf82** [comment]
See the tests running:

https://user-images.githubusercontent.com/2768415/141815888-eb6912f4-615d-4f3b-b1e7-a05868e0b80f.mp4

https://user-images.githubusercontent.com/2768415/141815895-c2f9bac4-c4f4-4a4e-8393-4427318de9ec.mp4

**Comment by idmarjr** [comment]
Not sure if I'm doing something wrong but one of the tests is failing here:

Screen Shot 2021-11-16 at 23 29 25
Screen Shot 2021-11-16 at 23 30 13

is this expected?

**Comment by wlsf82** [comment]
> is this expected?

Not it's not. Are you running the tests against your local environment?

Maybe I'll need to increase a timeout since the default one from Cypress might not be enough.

@idmarjr, have you tried more than once? If so, does it always fails on the same step?

**Comment by idmarjr** [comment]
Yes sir. I'm running it at localhost and tried to run it twice, once using `yarn test` and another using `yarn cy:open`, both fail. 

Maybe someone else can run the tests as well to double check it? 

CC @ArthurMota9 @miltonbsn or @oicramps

**Comment by wlsf82** [comment]
> Yes sir. I'm running it at localhost and tried to run it twice, once using `yarn test` and another using `yarn cy:open`, both fail. 

Maybe we can pair on it tomorrow so that I can investigate it further.

**Comment by wlsf82** [comment]
Oddly, only one test is failing.

The `beforeEach` hook runs before each test, as its name suggests.
This means that, for all other tests, all steps inside of it have passed.

@miltonbsn, maybe you can help us out here.

When visiting the relative URL `/#!/main` as a logged-in user, should a `GET` request always happen to retrieve the models of such user (`/models?userId=*`)?

**Comment by miltonbsn** [comment]
> Oddly, only one test is failing.
> 
> The `beforeEach` hook runs before each test, as its name suggests. This means that, for all other tests, all steps inside of it have passed.
> 
> @miltonbsn, maybe you can help us out here.
> 
> When visiting the relative URL `/#!/main` as a logged-in user, should a `GET` request always happen to retrieve the models of such user (`/models?userId=*`)?

Hi @wlsf82, yes every time you visite `/#!/main` we execute a GET request. https://github.com/brmodeloweb/brmodelo-app/blob/3e7b8309be21cd847421e5176040e1830af84077/app/angular/workspace/workspace.js#L47 Is it too slow?

**Comment by wlsf82** [comment]
@idmarjr, can you pull the new code I pushed today and try again, please?

Let's see if this commit https://github.com/brmodeloweb/brmodelo-app/pull/254/commits/02c5314f06e26d04daf4965b6b51138941ee4097 will fix it.

Cc @miltonbsn.

**Comment by idmarjr** [comment]
Nope. 02c5314 did not solve the issue. 😢 

Screen Shot 2021-11-17 at 19 48 55
Screen Shot 2021-11-17 at 19 49 08
Screen Shot 2021-11-17 at 19 52 51

**Comment by wlsf82** [comment]
> Nope. [02c5314](https://github.com/brmodeloweb/brmodelo-app/commit/02c5314f06e26d04daf4965b6b51138941ee4097) did not solve the issue. 😢

Right after line 10 (the failure), I see that there's a `GET` request to `http://localhost:3000/models`, while the test expects a request to `http://localhost:3000/models?userId=*`.

@miltonbsn, is there a "kind" of user who gets all the models instead of only its own?

**Review by miltonbsn — APPROVED** [review]

**Review by ArthurMota9 — APPROVED** [review]

**Comment by wlsf82** [comment]
To keep it documented, we discovered that, on @idmarjr's computer, the failure is related to the use of the experimental feature `cy.session`. Without it, all tests worked fine.

On everyone else's computer, `cy.session` works fine .

What happens to on Id's computer is that when using `cy.session`, the `getUserModels` request that we are trying to intercept never happens, failing the test in the `beforeEach` hook.

But, we decided to keep using the feature since it speeds up tests, and in the meanwhile, Id will try it out on another computer.

**Comment by wlsf82** [comment]
> To keep it documented, we discovered that, on @idmarjr's computer, the failure is related to the use of the experimental feature `cy.session`. Without it, all tests worked fine.
> 
> On everyone else's computer, `cy.session` works fine .
> 
> What happens to on Id's computer is that when using `cy.session`, the `getUserModels` request that we are trying to intercept never happens, failing the test in the `beforeEach` hook.
> 
> But, we decided to keep using the feature since it speeds up tests, and in the meanwhile, Id will try it out on another computer.

@bahmutov, any thoughts?

**Comment by bahmutov** [comment]
I would use cypress-data-session and be done with it

**Comment by wlsf82** [comment]
> To keep it documented, we discovered that, on @idmarjr's computer, the failure is related to the use of the experimental feature `cy.session`. Without it, all tests worked fine.
> 
> On everyone else's computer, `cy.session` works fine .
> 
> What happens to on Id's computer is that when using `cy.session`, the `getUserModels` request that we are trying to intercept never happens, failing the test in the `beforeEach` hook.
> 
> But, we decided to keep using the feature since it speeds up tests, and in the meanwhile, Id will try it out on another computer.

Just to keep it documented, the issue only happens when the server is pointing to a remote MongoDB. If the server points to a local MongoDB everything works fine.

**Pull request merged**
