### PR TITLE
Update gulpfile.js to Gulp4 syntax

### LINKED ISSUE #87: Atualizar ou migrar Gulp
- [ ]  ~gulp-autoprefixer   ^3.1.1  →   ^7.0.1~ ([Deprecated in favor of postcss usage](https://github.com/miltonbsn/brmodelo/pull/96/commits/e49a25bccf3c68782a738eedc27dc9fa02ec4189))
- [ ] gulp-sass           ^3.0.0  →   ^4.1.0 
- [ ] gulp-sourcemaps     ^1.9.1  →   ^2.6.5

### PR DESCRIPTION
**Pull request by idmarjr**
Close #87 
Close #98 

# Summary

- Update gulp syntax from old Gulp v3 to gulp V4;
- Rework tasks to a more straight forward flow
- Copy project dependencies to `./app/asets/` folder (Simplify deploy process in a future);
- Add task to optimize image files;
- Rewrite task that compile `scss` in `css` files;
   - Use postcss to handle css files
   - Use autoprefixer core project instead of gulp-autoprefixer
   - Use cssnano to minify css files;
- Use new `series` and `parallell()` functionalities from gulp4;
- Move development related packages to devDependencies instead of project dependencies in `package.json`;

## New gulp dependencies added:

- [gulp-plumber](https://www.npmjs.com/package/gulp-plumber);
- [gulp-postcss](https://www.npmjs.com/package/gulp-postcss);
- [autoprefixer](https://www.npmjs.com/package/autoprefixer);
- [cssnano](https://www.npmjs.com/package/cssnano);
- [gulp-imagemin](https://www.npmjs.com/package/gulp-imagemin);
- [gulp-newer](https://www.npmjs.com/package/gulp-newer);

## Extra

- Delete few .DS_Store files from the repo;
- Add .DS_Store to .gitignore;
- Change image folder name from `imgs/` to `img/`;
- Update images links to match the new folder name;
- Add `.app/assets/` as a static folder in `server.js`;

### CODE REVIEW

**Review by miltonbsn — COMMENTED** [review]
@idmarjr, it is missing bootstrap somewhere.

GET http://localhost:3000/assets/node_modules/bootstrap/dist/js/bootstrap.min.js net::ERR_ABORTED 404 (Not Found)

I use it to render modals:

image

**Comment by idmarjr** [comment]
Take it easy @miltonbsn This is still a draft pull request. A work in progress.
There's a lot of other things not working 😆

**Review by miltonbsn — APPROVED** [review]
Amazing work! Thank you very much.

Merge wherever you wish

**Comment by miltonbsn** [comment]
I'm sorry, I didn't see it was on draft 😆

> Take it easy @miltonbsn This is still a draft pull request. A work in progress.
> There's a lot of other things not working 😆

**Pull request merged**
