### PR TITLE
Fix feature to convert conceptual to logic model

### LINKED ISSUE #105: Not able to open a converted model
# Steps to reproduce

1. Create new or open a existent _conceptual model_;
1. Use the option _Gerar modelagem lógica_;
1. Save the new logic model and return to list of models;
1. Try to open the brand new converted model
1. BUG

The model does not open.
Console shows the follow errors:

```
Transition Rejection($id: 2 type: 6, message: The transition errored, 
detail: Error: Transition Rejection($id: 1 type: 4, message: This transition 
is invalid, detail: The following parameter values are not valid for 
state 'logic': [conversionId:undefined])) stateService.ts:537:14
    Angular 6
        _defaultErrorHandler
        c
        k
        $digest
        $apply
        compile
    jQuery 2
        dispatch
```

```
Tn@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:75896
wr.prototype.invokeHook@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:40380
wr.invokeHooks@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:39784
Pr.prototype.run@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:49815
jn.prototype.transitionTo@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:83129
jn.prototype.go@http://localhost:3000/angular-ui-router/release/angular-ui-router.min.js:11:81472
self.openModel@http://localhost:3000/angular/controller/modellist/listController.js:17:10
fn@http://localhost:3000/angular/angular.min.js line 251 > Function:4:241
e@http://localhost:3000/angular/angular.min.js:198:192
$eval@http://localhost:3000/angular/angular.min.js:154:468
$apply@http://localhost:3000/angular/angular.min.js:155:198
compile/</<@http://localhost:3000/angular/angular.min.js:198:276
dispatch@http://localhost:3000/jquery/dist/jquery.min.js:3:7537
add/r.handle@http://localhost:3000/jquery/dist/jquery.min.js:3:5620
stateService.ts:538:58
    Angular 6
        _defaultErrorHandler
        c
        k
        $digest
        $apply
        compile
    jQuery 2
        dispatch
        handle
```

## Screenshots

Screen Shot 2020-06-15 at 03 21 37

### PR DESCRIPTION
**Pull request by miltonbsn**
Fix #105 

# Steps to test

1. Create new or open a existent _conceptual model_;
1. Use the option _Gerar modelagem lógica_;
1. Save the new logic model and return to list of models;
1. Try to open the brand new converted model from list;

### CODE REVIEW

**Comment by miltonbsn** [comment]
Close #105

**Review by idmarjr — APPROVED** [review]
Tested locally. Works like a charm! 💙

**Comment by idmarjr** [comment]
---
Meanwhile I would like to suggest some good practices:

---

## Use a meaningful name to the pull request

Instead of use only the `Fix #105` as a name, lets try to name it in a meaningful way. In this case I would use something like:  
**Fix feature to convert conceptual to logic model**
This way is easy to understand the pull request purpose without need to navigate to another place (The issue `#105`in this case)

## Use `close #issue` in pull request description

If you add `Close #105` in the pull request description the issue will be automatically closed as soon as the pull request is merged into master. No need to add a individual comment to do it.

One more thing on this. The comment closes the issue immediately. It that, at this moment, the master branch still have the bug but the issue is already closed. If for whatever reason we need to delay the merge, we now have hole in the current project status.

---
Sorry, this is just me being picky. Still I believe those are useful tips. 😄

**Comment by miltonbsn** [comment]
> Meanwhile I would like to suggest some good practices:
> 
> ## Use a meaningful pull request name
> Instead of use only the `Fix #105` as a name, lets try to name it in a meaningful way. In this case I would use something like:
> **Fix feature to convert conceptual to logic model**
> This way is easy to understand the pull request purpose without need to navigate to another place (The issue `#105`in this case)
> 
> ## Use `close #issue` in pull request description
> If you add `Close #105` in the pull request description the issue will be automatically closed as soon as the pull request is merged into master. No need to add a individual comment to do it.
> 
> One more thing on this. The comment closes the issue immediately. It that, at this moment, the master branch still have the bug but the issue is already closed. If for whatever reason we need to delay the merge, we now have hole in the current project status.
> 
> Sorry, this is just me being picky. Still I believe those are useful tips. 😄

Amazing suggestion! Could we have like a guide? Maybe a contribution guideline.

**Comment by idmarjr** [comment]
@all-contributors add @miltonbsn for code, tests, bug and maintenance

**Pull request merged**
