### PR TITLE
Adds i18Next support to React

### PR DESCRIPTION
**Pull request by oicramps**
# Summary

Configures `react-i18next` to handle internationalization in the react codebase

**Depends on:** Typescript support to React #289

### CODE REVIEW

**Comment by idmarjr** [comment]
@oicramps We have some conflicts here. Other than that, is this good to go?

**Comment by oicramps** [comment]
> @oicramps We have some conflicts here. Other than that, is this good to go?

I'll solve the conflicts later today, and then we are good to go. I'll let you know when the PR is ready to merge

**Comment by oicramps** [comment]
@idmarjr I've solved the conflicts

**Review by idmarjr — APPROVED** [review]
go-to-go

**Review by ArthurMota9 — APPROVED** [review]

**Pull request merged**
