### PR TITLE
Refactor tests and increase coverage

### PR DESCRIPTION
**Pull request by wlsf82**
Besides login and model creation, we now have tests for the models' view (for edition, duplication, and deletion.)

**Note:** the test that duplicates a model is failing due to a translation issue (see the below screenshot)

Models view -- duplicates a model (failed)

For the results of all tests, see the following videos.

https://user-images.githubusercontent.com/2768415/143967782-df6ea4cf-c2c4-45fe-b37b-fe471808ec2b.mp4

https://user-images.githubusercontent.com/2768415/143967791-d1329949-e8f0-4bd7-8c87-65df35498a8e.mp4

https://user-images.githubusercontent.com/2768415/143967797-59685f45-555a-4935-bf9d-57ff02deaaca.mp4

### CODE REVIEW

**Comment by wlsf82** [comment]
Can anyone review this for me, please?

**Comment by idmarjr** [comment]
> Can anyone review this for me, please?

@wlsf82 We just merged #263  to `development` branch. 
I think it worth to merge development into your branch to check for conflicts and adjust the tests.

**Comment by ArthurMota9** [comment]
> > Can anyone review this for me, please?
> 
> @wlsf82 We just merged #263 to `development` branch. I think it worth to merge development into your branch to check for conflicts and adjust the tests.

@idmarjr I'm going to merge and fix the conflicts.

**Comment by wlsf82** [comment]
@idmarjr and @ArthurMota9, I've fixed it all and updated the PR description.

Can you review it, please?

**Comment by wlsf82** [comment]
> @idmarjr and @ArthurMota9, I've fixed it all and updated the PR description.
> 
> Can you review it, please?

I recommend reading my commits (not only the titles but also their descriptions.)

**Review by ArthurMota9 — APPROVED** [review]

**Pull request merged**
