### PR TITLE
Fix api and jest tests

### PR DESCRIPTION
**Pull request by miltonbsn**
# Summary

Fix remove model api and user jest unit tests

## Changes

- Replace mockingoose to native jest mocking
- Remove mockingoose dependency
- Fix remove model api
- Fix userService unit tests

### CODE REVIEW

**Review by ArthurMota9 — APPROVED** [review]

**Comment by miltonbsn** [comment]
@wlsf82 this fixes the remove model problem, however I think our update caused another collateral.

All cypress tests are failing to me. It seems we are not finding the login button.

Could you help me ?

https://user-images.githubusercontent.com/881231/145324898-e35da70f-7d75-47b5-af0a-5a022231bf48.mp4

**Comment by wlsf82** [comment]
> @wlsf82 this fixes the remove model problem, however I think our update caused another collateral.
> 
> 
> 
> All cypress tests are failing to me. It seems we are not finding the login button.
> 
> 
> 
> Could you help me ?
> 
> 
> 
> https://user-images.githubusercontent.com/881231/145324898-e35da70f-7d75-47b5-af0a-5a022231bf48.mp4
> 
> 
> 
> 
> 
> 

The test is looking for a button with the text Login, but on the video the text is Entrar. I suggest changing it to a `cy.get('button[type="submit"]')` so we don't depend on the text. What do you think?

**Comment by idmarjr** [comment]
> The test is looking for a button with the text Login, but on the video the text is Entrar. I suggest changing it to a `cy.get('button[type="submit"]')` so we don't depend on the text. What do you think?

@wlsf82 Does it make sense to use ~~`data-test=""`~~ `data-cy=""` attributes?

**Comment by wlsf82** [comment]
> > The test is looking for a button with the text Login, but on the video the text is Entrar. I suggest changing it to a `cy.get('button[type="submit"]')` so we don't depend on the text. What do you think?
> 
> 
> 
> @wlsf82 Does it make sense to use `data-test=""` attributes?

It does. Feel free to do that. I've put one example using data-cy, which Cypress gives preference.

**Pull request merged**
