### PR TITLE
Feature/webpack migration

### LINKED ISSUE #73: Add babel compiler to the project
# Intro
In order to improve browser compatibility we want to compile JavaScript code via [Babel](https://babeljs.io/). This way we can write modern code and still ship the product to users with not that new browsers.

# Output

- Compile modern Javascript code to _old fashion_ Javascript;
- `.balbesrc`file with proper configuration;
- Update `Readme.md` (if needed);

### LINKED ISSUE #172: Environment variables configuration
**Is your feature request related to a problem? Please describe.**
We have some environment variables configured and an opportunity to create new ones in order to simplify the development flow by centralizing this kind of information:

- Database URL
- API URL
- API port
- Secrets

If I check out the project to contribute, I have no idea of which env variables are necessary to run the project.

**Describe the solution you'd like**
Implement and configure the [dotenv](https://github.com/motdotla/dotenv) library and create an `env.example` file to list the variables needed by the project.

**Describe alternatives you've considered**
Specify the environment variables that the application needs in the `readme` file, and then the developer should configure it in your development environment. This alternative is easier to implement but is not scalable

### LINKED ISSUE #179: Remove remaining instances of sweet-feedback
# Summary 

[Sweet-feedback](https://www.npmjs.com/package/sweet-feedback) is a feedback markup dependency used at **BR Modelo Web** since the beginning its existence. unfortunately the package is not supported anymore and [Bootstrap](https://www.npmjs.com/package/bootstrap) have a similar solution built in it's core. Due to this, there's no reason to keep [sweet-feedback](https://www.npmjs.com/package/sweet-feedback) as a project dependency

Due to that we need to remove it from [`package.json`](https://github.com/brmodeloweb/brmodelo-app/blob/development/package.json), remove it's markup in remaining pages and use Bootstrap feedback module instead.

# Desired output

- [x] d5b4f5d Remove [sweet-feedback](https://www.npmjs.com/package/sweet-feedback)  from  [`package.json`](https://github.com/brmodeloweb/brmodelo-app/blob/development/package.json)
- [x] d5b4f5d Remove CSS link from `<head>`
- [x] d5b4f5d Remove `@import` from `angular/index.js`
- [x] 8e10ce4 Replace `app/angular/conceptual/conceptual.html` markup with Bootstrap feedback module  
- [x] 8e10ce4 Replace `app/angular/conceptual/logic.html` markup with Bootstrap feedback module  
- [x] 8e10ce4 Replace `app/angular/view/conceptual.html` markup with Bootstrap feedback module  
- [x] 8e10ce4 Replace `app/angular/view/logic.html` markup with Bootstrap feedback module  

# Preview
Screen Shot 2021-07-11 at 16 53 25

### LINKED ISSUE #180: Editor sidebar behavior
# Summary

In the editor view (Logic and Conceptual) we provide relevant information about the selected element to users at the right sidebar. In order to prioritize a larger workspace by default the sidebar behavior is stay hidden and only if user click in the "expand arrow" they will see it's content. 

Problem with that is: users are completely missing the sidebar. This is a big problem cos part of crucial **BR Modelo Web** functionalities live in the sidebar

## Desired output

As a quick solution to this problem and a way to learn based in user behavior, we need to invert the functionality behavior. If users need more space to work they can hide the sidebar using the arrow.

- [ ] Default behavior when open the editor is: Show the right sidebar expanded
- [ ] Add a _empty state_ block to be visible when user have no element selected

# Screenshots
| Hidden sidebar | Expanded sidebar | Expanded sidebar with element selected |
| --------------- | ------------------ | ----------------------------------------- |
| Screen Shot 2021-07-11 at 17 07 17 | Screen Shot 2021-07-11 at 17 07 20 | Screen Shot 2021-07-11 at 17 07 23 |

### LINKED ISSUE #183: "Report bug" improvements
# Summary

Recently we introduced a option to users report bugs and/or request new product features. This feature have few implementation issues that need to be improved:

## Improve `:hover` state

When hovering the _bug_ icon we use a small rotate transition between states. This transition can result in a back-and-forward animation loop depending of the mouse pointer position (See attached git). This behavior should not happen

Jul-11-2021 18-19-59

## `.br-help` link visible on print version

The report bug/request feature icon (plus link) is currently visible in the printable version of a modal (See attached image). We need to hide this option when choose the print model option

Screen Shot 2021-07-11 at 18 20 45

### LINKED ISSUE #188: O clique duplo em um elemento deveria abrir a janela de edição.
O clique duplo em um elemento deveria abrir a janela de edição. Eu tive que abrir o seu TCC para descobrir como fazia para mudar o nome de um elemento.

### PR DESCRIPTION
**Pull request by miltonbsn**
# Summary

In a effort to modernize our code and implementation we're removing Gulp and introducing Webpack to deal with development dependencies. During this change we're also rewriting part of our code using [ES6](http://es6-features.org/#Constants) / [ES2021](https://h3manth.com/ES2021/).

Various bug fixes and some product improvements are also taking place in this merge request since the cost benefit of implement those changes using the old stack and migrate later was not worth it.

# List of changes

- [x] Remove outdated Gulp scripts
- [x] Add [Webpack](https://webpack.js.org/) as bundler (Close #73)
- [x] Environment variables configuration (Close #172)
- [x] Allow `.jsx`
- [x] Create components for:
   - [x] Create modal
   - [x] Delete modal
   - [x] Rename modal
   - [x] `.model-properties` sidebar (Conceptual)
   - [x] `.model-properties` sidebar (Logic) 
- [x] Improve visuals for element selections
- [x] Close #183 
- [x] Close #179
- [x] #217 
- [x] #220 
- [x] #222 
- [x] #224
- [x] #225 
- [x] #235
- [x] Close #180

### CODE REVIEW

**Comment by miltonbsn** [comment]
@all-contributors please add @oicramps for code

**Comment by miltonbsn** [comment]
@all-contributors please add @oicramps for review

**Comment by miltonbsn** [comment]
@all-contributors please add @idmarjr  for maintenance

**Comment by miltonbsn** [comment]
@all-contributors please add @telmotrooper for code

**Comment by miltonbsn** [comment]
@all-contributors please add @ArthurMota9  for code

**Comment by miltonbsn** [comment]
@all-contributors please add @ArthurMota9 for review

**Review by idmarjr — APPROVED** [review]
👶  🍼  Nasceu!

**Pull request merged**
