### PR TITLE
Introduce duplicate model option

### LINKED ISSUE #124: Duplicate model
# Summary 

Users need to generate a new model based in a pre-existing model.

# Output

- User interface to duplicate model (List view)
- User interface to duplicate model (Model edit view);
- Pre-define duplicated model name based in original name + current date (Allow user edit during duplicate process)

### PR DESCRIPTION
**Pull request by idmarjr**
# Summary

Close #124 

Based in user feedback we're adding a option to quickly duplicate a model. This option is accessible from the list of models as well from the edit model page (Logic and conceptual). By clicking in the duplicate icon user is prompt with a modal with the option to choose the model name.

# List of changes

- `main.html`
   - [x] Add duplicate option to each item in the list
   - [x] Call modal on click;
- `logic.html`
   - [x] Add duplicate option to `.tool-icons` toolbar;
   - [x] Call modal on click;
- `conceptual.html`
   - [x] Add duplicate option to `.tool-icons` toolbar;
   - [x] Enable modal to open on click
- `duplicateModelModal.html `
   - [x] Modal markup;
   - [x] Automatic fill new model name with `currentName-copy`;
- `duplicateModelModalController.js`
   - [x] Basic logic (Copy+paste from `newModelModalController.js`);
   - [x] Automatic fill new model name with `currentName-copy`;

# Screenshots

## Modals list

Screen Shot 2020-08-09 at 5 53 36 PM

## Conceptual workplace

Screen Shot 2020-08-09 at 5 53 57 PM

## Logic workplace

Screen Shot 2020-08-09 at 5 54 03 PM

## Duplicate modal

**T.B.D.**

### CODE REVIEW

**Comment by idmarjr** [comment]
@miltonbsn Your time to shine!

**Review by miltonbsn — APPROVED** [review]

**Comment by miltonbsn** [comment]
@idmarjr

**Comment by idmarjr** [comment]
@miltonbsn 
I'm able to create multiple copies from a model that have the same name.
Should we have any kind of validations to avoid models with same name?

By the way, I'm fine if we decide to deal with this in another pull request.

Screen Shot 2021-02-03 at 9 44 57 PM

**Comment by miltonbsn** [comment]
> @miltonbsn
> I'm able to create multiple copies with the same name from a model.
> Should we have any kind of validations to avoid models to have same name?
> 
> By the way, I'm fine if we decide to deal with this in another pull request.
> 
> Screen Shot 2021-02-03 at 9 44 57 PM

Vou criar uma outra issue para isso, uma vez que que também da de criar modelagem com o mesmo nome "manualmente". Um ótimo ponto. Vou implementar isso nos próximos dias.

**Pull request merged**
