### PR TITLE
Migrate markup to Bootstrap

### PR DESCRIPTION
**Pull request by idmarjr**
# Summary 

Since one of the objectives is upgrade to a newer Bootstrap, it make sense to move our markup to the standard used by the version we current have. This way the migration to a new version will (probably) be less complicated.

This process will imply in remove a good portion of old custom CSS used as well tweak some interfaces since we're already dealing with deep changes in the app.

## To do
- [x] ~Public pages: Login~* (Partially done here: 0391c39)
- [x] ~Public pages: Create user~* (Partially done here: 0391c39)
- [x] Use Bootstrap at application header
- [x] Use bootstrap at table in `main.html`;
- [x] Migrate _conceptual_ view to use Bootstrap
- [x] Migrate _logic_ view to use Bootstrap
- [x] Add "Rename" functionality to the list in `main.html` (Partially ready: a7ae2b5)
- [x] Remove `reset.scss` to avoid conflicts with Bootstrap styles
- [x] Remove custom styles for buttons that were not being used;
- [x] Rework feedback position and styles;

*: We're not touching public pages at the moment cos the [login/create user will be changed soon](https://github.com/brmodeloweb/brmodelo-app/issues/103).

## Product changes
- New Workspace header;
- New workspace toolbar;
- New interaction to rename model (Partially done);

## Screenshots
Screen Shot 2020-06-09 at 22 19 50
Screen Shot 2020-06-09 at 22 18 55

### CODE REVIEW

**Comment by idmarjr** [comment]
@miltonbsn I'm cleaning some stuff and I have a question:

> Are we still using [jquery-nice-select](https://www.npmjs.com/package/jquery-nice-select) somewhere? I can see a bunch of CSS declarations related to `.nice-select` but looks like there's no JS code at all calling it.

I can see few references to `dropdown-tmp` but I dont think it's related to `jquery-nice-select`.

**Update:** Fix 9b48b06 and 8e86227

**Comment by miltonbsn** [comment]
@idmarjr I don't know if you completed the work on this screen but as you requested my review here are the things I missed:

1) ~The print button~ 012ea9a 

image

2) ~The "Gerar modelagem lógica button"~ 383996e 

image

3) ~Just opinion) Visually, I liked a lot what you are proposing but I think we lost an important working area (around 25%). I instantly felt the difference on my 13 inch screen~  2de1e25 
> Update by @idmarjr : _Not fully solved but some changes to save vertical space were made._

image

**Review by miltonbsn — COMMENTED** [review]
1) ~This button should be shown only in the logic view~ ac8a479 

image

2) ~I think we removed the print css by mistake~  69a015f 

image

3) ~This button should be shown only in the conceptual view~ 5362158

image

4) ~Print button is not working on logic view~ b3bb910

5) ~Is it possible to change the blue border to the green one?~ 7519674
> Update by @idmarjr: Accessibility issue. Read the commit message to know more.

image

* As a user I really missed this modeling area, I pick an example from draw.io where they try to optimize as much as possible the space. But that's ok, this is just a opinion, we can come back to this later:
> Update by @idmarjr: I agree with you on it although I don't think this should be a blocker since user can use zoom or and scroll and have access to the full model. There are multiple ways to regain this vertical space we can explore in a near future.

> P.S .: [IMHO](https://www.urbandictionary.com/define.php?term=IMHO) improve the zoom behavior (It's a bit rustic right now) will have much more impact in the user experience than save 50 vertical pixels.

image

image

**Comment by idmarjr** [comment]
@miltonbsn 
All major points are now fix.
Please take a look in my notes in your comments above.

~Also, I still need a statement about this: https://github.com/miltonbsn/brmodelo/pull/102#issuecomment-642197175~

**Comment by idmarjr** [comment]
Also, need your help to finish the Rename modal:  a7ae2b5

**Review by miltonbsn — APPROVED** [review]
Amazing as always. Thank you very much for all your support.

**Comment by miltonbsn** [comment]
> nice-select

I did't find as well. We can remove this dependency.

**Comment by miltonbsn** [comment]
> a7ae2b5

Ah ok, I will start working on it. Should be ready by tomorrow! But we can merge and follow that in another thread.

**Comment by idmarjr** [comment]
@all-contributors please add @idmarjr for code, design, and projectManagement

**Pull request merged**
