### PR TITLE
Login page: Change language selector styles

### PR DESCRIPTION
**Pull request by idmarjr**
# Summary

- Move away from only flags approach
- Use text instead;
- Add header to language section
- Add globe icon
- Never translate language name (Accessibility reasons)
- Simplify translations

# Screenshots

Screen Shot 2021-12-12 at 13 52 33

### CODE REVIEW

**Comment by wlsf82** [comment]
There's a test that switches the languages based on the flag. Remember to run them and make any adjustments before merging.

**Comment by ArthurMota9** [comment]
> There's a test that switches the languages based on the flag. Remember to run them and make any adjustments before merging.

You're right @wlsf82 ! If you want, I can adjust the tests @idmarjr.

**Comment by idmarjr** [comment]
> [...] I can adjust the tests @idmarjr.

@ArthurMota9 
I appreciate your availability man but don't worry, I can take a look on it.
Still I will request your review for it. :)

**Comment by idmarjr** [comment]
@wlsf82 can you please review 9790191231781ba81a54879262b73d31abab0aa9

**Comment by wlsf82** [comment]
> @wlsf82 can you please review 9790191231781ba81a54879262b73d31abab0aa9

@idmarjr, `lang-ptbr` is not that odd, but `lang-enus` is just weird.
What about `lang-pt-br` and `lang-en-us`?

Other than that, it LGTM.

**Comment by idmarjr** [comment]
>[...] What about `lang-pt-br` and `lang-en-us`?

@wlsf82  Done.

**Review by ArthurMota9 — APPROVED** [review]

**Pull request merged**
